### ISSUE TITLE
Assembler

### ISSUE THREAD

**Issue by zignig** [cr1901/boneless-sim#1]
You might be interested in some work I have been doing on a text assembler.

https://github.com/zignig/Boneless-CPU/tree/assembler

**Comment by cr1901** [comment]
Hi @zignig, thank you for the interest. I have commit access to upstream Boneless-CPU; the simulator as-is targets an earlier version of Boneless and [needs to be modified](https://github.com/whitequark/Boneless-CPU/pull/1) before all my stuff is merged.

I should probably get on that, since I'm trying to pop stuff off my yak stack...

**Comment by zignig** [comment]
mmm yak stack. I too have  a list of things that need shaving. This is a programmatic diversion from another YAK that has been getting furry recently (https://cqparts.github.io/)

I found the boneless CPU and wrote an assembler. Actually looked at the existing issues and found that you had already written a simulator.

I have found some issues already , eg , LD does not increment the PC before it is run.

How do you want to proceed ? , @whitequark is a busy life-form, I'm sure that she would rather progress is made to ensure the awesome.

I would like to continue to write an assembler, is it possible to merge the simulator as is and head towards testing that will run simulator->gateware->FPGA ?

Her quarkyness can update the ISA ongoing and we can update in turn.

My pipe-dream goal is to write a resident FORTH and/or have an dis/assembler|monitor  for control plane usage.
